### ISSUE TITLE
[BUG] Readme examples missing comma

### ISSUE THREAD

**Issue by guyluz11** [shan-shaji/day_picker#11]
**Describe the bug**
In the readme file the examples missing a `,` comma.

**To Reproduce**
1. Go to https://github.com/shan-shaji/day_picker/edit/master/README.md

**Screenshots**

First place:

![image](https://user-images.githubusercontent.com/9304740/180608628-6c8ae403-c2e9-4b96-8fb2-2eb21e55d277.png)

Second place:

![image](https://user-images.githubusercontent.com/9304740/180608641-1f645442-8cd0-48af-8991-c24c6f47cb98.png)

**Comment by shan-shaji** [comment]
@guyluz11 , Thanks for opening an issue. Would you mind working on this?

**Comment by guyluz11** [comment]
Sure Assignees  that to me
