### ISSUE TITLE
Improve pub points

### ISSUE THREAD

**Issue by shan-shaji** [shan-shaji/day_picker#13]
Visit https://pub.dev/packages/day_picker/score to know more details about the pub dev score.

<img width="500" alt="Screenshot 2022-10-09 at 3 11 13 PM" src="https://user-images.githubusercontent.com/42430941/194749663-2740fda7-c60f-41d3-bcd9-dd8fb89324ab.png">

**Comment by guyluz11** [comment]
Looks good now :D

This issue can be closed

**Comment by shan-shaji** [comment]
Thanks for raising this @guyluz11 .
