### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AbnerRibeirodaSilva** [shan-shaji/day_picker#14]
when using SelectWeekDays in a dialog, close the diolog and enter it again the selected days remain selected unless I leave the page and come back again, I need to somehow reset the selectedDays list

**Comment by shan-cnd** [comment]
Hey @AbnerRibeirodaSilva  thanks for opening the issue and sorry for the late reply. Would you like to work on it?

**Comment by shan-shaji** [comment]
@AbnerRibeirodaSilva this is fixed in #15
