### ISSUE TITLE
Option to change SelectWeekDays after widget got created

### ISSUE THREAD

**Issue by guyluz11** [shan-shaji/day_picker#15]
Feature request 
I am trying to change selected weekdays from outside after SelectWeekDays got created.

SelectWeekDays widget has its own state so just calling it again with different `days` will not change anything.

Let's add a way for programmer to change selected days from outside after SelectWeekDays got created, for example add a method to change days which will setState of days.

**Comment by shan-shaji** [comment]
Thank you, @guyluz11, for bringing up the issue. Are you interested in taking on the task? I, unfortunately, won't be available to work on it until the upcoming weekends.
